-- Add store_config table for generic key-value POS settings
-- Run in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS store_config (
  id        BIGSERIAL PRIMARY KEY,
  store_id  BIGINT NOT NULL REFERENCES stores(id),
  key       TEXT NOT NULL,
  data      JSONB,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(store_id, key)
);
CREATE INDEX IF NOT EXISTS idx_store_config_store ON store_config(store_id);

-- Disable RLS (service_role bypasses anyway, but be safe)
ALTER TABLE store_config DISABLE ROW LEVEL SECURITY;

-- Also disable RLS on all existing tables to fix write issues
ALTER TABLE employees DISABLE ROW LEVEL SECURITY;
ALTER TABLE vendors DISABLE ROW LEVEL SECURITY;
ALTER TABLE brands DISABLE ROW LEVEL SECURITY;
ALTER TABLE categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE departments DISABLE ROW LEVEL SECURITY;
ALTER TABLE products DISABLE ROW LEVEL SECURITY;
ALTER TABLE customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE order_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE deliveries DISABLE ROW LEVEL SECURITY;
ALTER TABLE delivery_notes DISABLE ROW LEVEL SECURITY;
ALTER TABLE service_jobs DISABLE ROW LEVEL SECURITY;
ALTER TABLE service_techs DISABLE ROW LEVEL SECURITY;
ALTER TABLE companies DISABLE ROW LEVEL SECURITY;
ALTER TABLE time_clock DISABLE ROW LEVEL SECURITY;
ALTER TABLE sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_order_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE serial_pool DISABLE ROW LEVEL SECURITY;
ALTER TABLE stores DISABLE ROW LEVEL SECURITY;
ALTER TABLE counters DISABLE ROW LEVEL SECURITY;
